### ISSUE TITLE
Idiomatic logging of requests and responses

### ISSUE THREAD

**Issue by 0x6e6562** [apollostack/graphql-server#216]
What's the idiomatic way to log gql requests and responses?

I've seen that you can supply a `logFunction` to the `graphql-server-express` instance, but this is fired once for each portion of the request with different keys to denote the query, the operation, variables and other data.

Is the idea that the supplier of the callback should accumulate these keys so that it in turn can generate a single log event for the application?

What I'd like to configure is a logger that pretty prints each client request as a single log entry.

**Comment by helfer** [comment]
@0x6e6562 IIRC the log function gets called a bunch of times with different keys. The one you're interested in is the `info.query`, `info.variables` etc. keys, which will have the info you're looking for. An alternative way to do logging is to add a middleware before the server.

**Comment by 0x6e6562** [comment]
@helfer Thanks very much for the heads up - I think I'll go with a middleware to log this out.

**Comment by dandv** [comment]
This has been working well for me:

```js
const server = new Apollo.ApolloServer({
  schema: ...,
  formatError: error => {
    logger.warn(error);
    return error;
  },
  formatResponse: (response, query) => {
    logger.info('GraphQL query and variables', {
      query: query.queryString,
      vars: query.variables,
    });
    return response;
  },
});
```

**Comment by dandv** [comment]
# apollo-server 2.1.1 and later

Note that starting with apollo-server 2.2.1 (or possibly earlier), the method I described in my previous comment no longer works, because the `query` parameter is [no longer](https://github.com/apollographql/apollo-server/pull/1414#issuecomment-449877737) passed to `formatResponse`.

I still haven't found clear documentation on how to log queries. Other hacks have been suggested [in this StackOverflow question](https://stackoverflow.com/questions/54273194/log-apollo-server-graphql-query-and-variables-per-request) I asked.

**Comment by leehankyeol** [comment]
To anyone frustrated, you can actually pull the requestContext from `formatResponse`. https://github.com/apollographql/apollo-server/pull/1414#issuecomment-553445945
