### ISSUE TITLE
Payload Too Large

### ISSUE THREAD

**Issue by manuelfink** [apollostack/graphql-server#288]
I just tried to fire a bunch of mutations against the graphql-server. This now throws an error `413 Payload Too Large`. How can I increase the payload?

**Comment by manuelfink** [comment]
thought this is a problem of graphql-server however it is caused by bodyParser and resolved through `bodyParser.json({limit: '50mb'})`

**Comment by christianTrepp** [comment]
Thanks for the info! Had same problem.

**Comment by gburchfield** [comment]
Wow, I originally thought my `413 Payload Too Large` response had a root cause from my nginx proxy server especially since the documentation said it's `413` codes may be displayed differently in the browser.  Long story short after a ton of debugging I fell onto this feed and found the root cause was the default `bodyParser.json()` limit of `100kb`.  I set that just like @manuelfink and it fixed my problem!

**Comment by rmacuna** [comment]
Hello I'm having the same issue but I have no luck with my code:

```javascript
app.use(express.json({ limit: '50mb' }))

```

**Comment by harbolaez** [comment]
trying above and no luck, any idea?

**Comment by jekabs-karklins** [comment]
`app.use(express.json({ limit: '50mb' }));`
worked for me
